### ISSUE TITLE
Quest .BIN Information #1

### ISSUE THREAD

**Issue by suzaku830** [ricochhet/MHF-Quest-Resources#1]
I don't know you know already this info or not.
"d" is day and "n" is night.
"0" is warm season and "1" is cold, "2" is breeding.

Quest info is insde mhfinf.bin, not mhfdat.bin.

**Comment by ricochhet** [comment]
Thank you for this information, I really appreciate it!

**Comment by suzaku830** [comment]
Are you trying to look into quest file, or just combining Refrontier with QuestEditor to one tool?
I can provide more infromation, like which offset have what meaning, how to create/change map, for further improvement.

**Comment by ricochhet** [comment]
I made this quest editor. Of course I know what each offset means.
