### ISSUE TITLE
mhfinf.bin info

### ISSUE THREAD

**Issue by NotTheLegend** [ricochhet/MHF-Quest-Resources#2]
I figured I'd share the progress I've made with mhfinf over the last week. [repo link](https://github.com/NotTheLegend/FrontierDump/blob/main/FrontierDump/FrontierDump/Program.cs) But there's still a lot of data I haven't been able to piece together yet tho

**Comment by ricochhet** [comment]
This looks nice! 

My only questions would be, how does this differentiate from ReFrontier in it's current state? Albeit I haven't actually messed with this part of ReFrontier very much, so I could be wrong on that entirely. 

Based on the quick skimming I did, it seems this currently only reads through the mhfinf.bin, and output a CSV. I assume you plan to allow the user to edit the output CSV, and then inject that back into at mhfinf.bin, at some point in the future, yes?

**Comment by NotTheLegend** [comment]
tbh, in its current form, its not much different from the quest dump part of frontier, the only big thing is that it parses offsets from the file instead, the 13 refrontier has are outdated?/wrong(+ there's 44 offsets in total in the mhfinf.bin from the archive) and filled in some of the unknown data (fileName & location + 4 more quest strings)

Down the line, i'll end up adding the ability to edit/inject stuff back in

**Comment by ricochhet** [comment]
I see. I haven't messed with that part of ReFrontier, this is good to know! If you have the time, and are interested, you could fork and modify the ReFrontier tools that this project uses for better support too. Or you could fork ReFrontier from [here](https://github.com/mhvuze/ReFrontier). Either way, thank you for the research and work you put in so far! The more help we have the faster things move.
