### ISSUE TITLE
QuestTool doesnt actually modify the quest.bin

### ISSUE THREAD

**Issue by imkedux** [ricochhet/MHF-Quest-Resources#6]
i have the debug variable on false and the quest ends in d0
![image](https://user-images.githubusercontent.com/90074746/134258003-8d44199b-9b15-45f7-85f5-9f42d66580c2.png)

**Comment by ricochhet** [comment]
Fixed in commit 95e113edbce71fb81e5b05f53597555752b2c4df

**Comment by imkedux** [comment]
it worked but the output folder got deleted you have to create the foulder in order to make it work, i also wanna add that the debug variable its on /QuestTool.cs and not in /QuestWriter.cs

**Comment by imkedux** [comment]
well in game doesnt change nothing just in the .log

**Comment by ricochhet** [comment]
Did you actually test it, or are you just looking from the quest board.

**Comment by imkedux** [comment]
i dont know japanese,i tested in mission with 2 quests at least the objective,monster and location dont seems to work
