### ISSUE TITLE
ReFrontierDataTool modshop corrupts the mhfdat.bin file

### ISSUE THREAD

**Issue by imkedux** [ricochhet/MHF-Quest-Resources#7]
i suppose its corrupted when i enter in the game just shows this and then crashes, i tried with the vanilla mhfdat and the one from progression enabler
![image](https://user-images.githubusercontent.com/90074746/134436107-08ae2056-47f7-41c6-a872-8ad86f06b3dd.png)

**Comment by imkedux** [comment]
also i have to dump the file with refrontier to make the command to work i tried compressing the file again tho

**Comment by ricochhet** [comment]
This does not happen for me. I do not do anything with these tools either. I integrate them into mine so I can work with things better. Look for info here: [https://github.com/mhvuze/ReFrontier](https://github.com/mhvuze/ReFrontier)
